# Generated by Django 3.1.3 on 2020-11-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201121_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='owen',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена'),
        ),
    ]
