# Generated by Django 3.1.3 on 2020-11-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201121_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='store_max',
            field=models.CharField(default=256, max_length=255, verbose_name='Обьем встроенной памяти'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd_volume_max',
            field=models.CharField(max_length=255, verbose_name='Максимальный объем SD карты'),
        ),
    ]
